# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import webinterface.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analysis',
                'verbose_name_plural': 'Analyses',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('site_calibration_allowed', models.BooleanField(default=False)),
                ('site_calibration_file', models.FileField(upload_to=webinterface.models.ProjectManager.getUploadPath)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Turbine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('manufacturer', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=120)),
                ('diameter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hub_height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bins', models.CharField(max_length=300)),
                ('powerInKillowats', models.CharField(max_length=300)),
                ('oneMeterStrip', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='turbine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webinterface.Turbine'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webinterface.Project'),
        ),
    ]
