# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 18:54
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        HStoreExtension(),
    ]
