# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 19:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0002_auto_20160323_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turbine',
            name='stripes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
