# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0003_project_combineddatafile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsondatafile',
            name='projectID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
