# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0003_turbine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turbine',
            name='bins',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='turbine',
            name='powerInKillowats',
            field=models.CharField(max_length=300),
        ),
    ]
