# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0003_project_turbine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webinterface.Project')),
            ],
            options={
                'verbose_name_plural': 'Analyses',
                'verbose_name': 'Analysis',
            },
        ),
    ]
