# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 19:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0004_column_datafile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='columnSeparator',
        ),
        migrations.AlterField(
            model_name='datafile',
            name='badDataValues',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='columnSets',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='rewsLevels',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='rowsToSkip',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='selectors',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
