# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 19:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0005_auto_20160324_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='columns',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
