# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0005_project_sitecalibrationdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
