# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0006_auto_20160324_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='positionInFile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
