# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 20:32
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0007_column_positioninfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataFile',
        ),
        migrations.AddField(
            model_name='project',
            name='datafiles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300, null=True), blank=True, null=True, size=None),
        ),
    ]
