# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0007_analysis_deriveddatafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='tableRows',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webinterface.JsonDataFile'),
        ),
        migrations.AddField(
            model_name='jsondatafile',
            name='analysisID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
