# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0008_auto_20160324_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='directory',
            field=models.CharField(default='C:\\Users\\Liam\\Desktop\\WebServier\\GroupProject', max_length=600),
        ),
    ]
