# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0008_auto_20160416_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='analysisType',
            field=models.IntegerField(blank=True, choices=[(1, 'Synchronised'), (2, 'Derived')], null=True),
        ),
    ]
