# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import webinterface.models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0009_project_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mastFile',
            field=models.FileField(blank=True, null=True, upload_to=webinterface.models.ProjectManager.getMastFilePath),
        ),
    ]
