# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0009_analysis_analysistype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='directory',
            field=models.CharField(default='E:\\Users\\Graham\\Desktop\\uni\\yr 3\\Group Project\\Group Project\\GroupProject', max_length=600),
        ),
    ]
