# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0010_project_mastfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webinterface.Project'),
        ),
    ]
