# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0010_auto_20160418_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='correlationPlot',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='analysis',
            name='distributionPlot',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='analysis',
            name='fftPlot',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='analysis',
            name='powerCurvePlot',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='directory',
            field=models.CharField(default='C:\\Users\\Liam\\Desktop\\WebServier\\GroupProject', max_length=600),
        ),
    ]
