# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 13:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0011_column_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='windFile',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
