# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 14:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0012_project_windfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='windFile',
            new_name='lidarDataFile',
        ),
        migrations.AddField(
            model_name='project',
            name='powerDataFile',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='windDataFile',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
