# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import webinterface.models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0013_auto_20160325_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='siteCalibrationFile',
            field=models.FileField(blank=True, null=True, upload_to=webinterface.models.ProjectManager.getSiteCalibrationFilePath),
        ),
    ]
