# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import webinterface.models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0014_project_sitecalibrationfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lidarFile',
            field=models.FileField(blank=True, null=True, upload_to=webinterface.models.ProjectManager.getLidarFilePath),
        ),
        migrations.AddField(
            model_name='project',
            name='powerFile',
            field=models.FileField(blank=True, null=True, upload_to=webinterface.models.ProjectManager.getPowerFilePath),
        ),
    ]
