# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0015_auto_20160402_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='dataLoggerCalibrationOffset',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='column',
            name='dataLoggerCalibrationSlope',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='column',
            name='instrumentCalibrationOffset',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='column',
            name='instrumentCalibrationSlope',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='column',
            name='measurementHeight',
            field=models.FloatField(default=0.0),
        ),
    ]
