# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 13:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0017_auto_20160404_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='datafiles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=2000, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='directory',
            field=models.CharField(default='C:\\Users\\Liam\\Desktop\\WebServier\\GroupProject', max_length=600),
        ),
    ]
