# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 13:53
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0018_auto_20160407_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='datafiles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=2000, null=True), blank=True, max_length=2000, null=True, size=None),
        ),
    ]
