# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 19:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0020_remove_project_datafiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='combinedDataFile',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
