# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 12:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import enumfields.fields
import windAnalysis.ppaTypes


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0021_project_combineddatafile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('directory', models.CharField(max_length=500)),
                ('fileType', enumfields.fields.EnumField(enum=windAnalysis.ppaTypes.FileType, max_length=10)),
                ('columns', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
